### ISSUE TITLE
Emissive blocks don't work properly under Godot 4.1.2

### ISSUE THREAD

**Issue by 0xhckr** [jon-heard/Godot-MagicaVoxel-Importer-with-Extensions#3]
![image](https://github.com/jon-heard/Godot-MagicaVoxel-Importer-with-Extensions/assets/5733032/6eca9327-7579-4601-8eff-9b5de1e25fcf)
Not sure if this worked before or not but I'm just creating an issue to document it

![image](https://github.com/jon-heard/Godot-MagicaVoxel-Importer-with-Extensions/assets/5733032/852366e5-f40c-4151-85d7-3ea1010504b7)
Here's how it looks in magicavoxel btw

(and yes, I've reloaded the scene a number of times too)

**Comment by ZsoltHevesi** [comment]
If that is a MagicaVoxel Render, it is simply impossible to port those materials anywhere else. Just the way MagicaVoxel works.
